/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Capture
 #	author : miyako
 #	2016/10/27
 #
 # --------------------------------------------------------------------------------*/



// --- Device
void CAPTURE_DEVICE_Get_default(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_DEVICE_LIST(sLONG_PTR *pResult, PackagePtr pParams);

// --- Snap
void CAPTURE_Snap(sLONG_PTR *pResult, PackagePtr pParams);
